### PR TITLE
producttooltip.php updation

### PR DESCRIPTION
**Pull request by deepankar321**
hey,
here i have added one more configuration in this file to show number of people added product on their cart and how many people watching this at that moment . it will be helpful to show product popularity direct to customer .
i have mentioned " /*added by me */ " comment whereever i have changed the code.

### CODE REVIEW

**Comment by gRoussac** [comment]
Hi,

Thank you for your PR. Can you pleae make it again on dev branch please ?

Regards

**Comment by deepankar321** [comment]
Hi,

I have pulled request on dev branch for this file.

Thanks
Regards

**Comment by jeromenadaud** [comment]
Hi, still on master branch,

When you create you PR, you can choose the branch, please choose dev branch.
You also may be interested in http://doc.prestashop.com/display/PS16/How+to+write+a+commit+message

Best regards

**Comment by maximebiloe** [comment]
Hello,

Thanks for your PR #6.
As it's a duplicate, let me close this one.

Best regards

**Pull request closed without merging**
